#!/usr/bin/env python3
"""Embed native SM70 TileLang cubins as dependency-free C string arrays."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def emit(name: str, path: Path) -> str:
    data = path.read_bytes()
    lines = []
    for offset in range(0, len(data), 32):
        lines.append('"' + "".join(f"\\x{byte:02x}" for byte in data[offset : offset + 32]) + '"')
    digest = hashlib.sha256(data).hexdigest()
    return (
        f"// {path.name} bytes={len(data)} sha256={digest}\nalignas(8) static constexpr char {name}[] =\n"
        + "\n".join(lines)
        + ";\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--partial", type=Path, required=True)
    parser.add_argument("--combine", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = (
        "// Generated by tools/v100/embed_tilelang_cubin.py. Do not edit.\n"
        "// Native SM70 cubins compiled from the manifest-pinned TileLang CUDA export.\n\n"
        + emit("kDFlashTileLangPartialCubin", args.partial)
        + "\n"
        + emit("kDFlashTileLangCombineCubin", args.combine)
    )
    args.output.write_text(content)


if __name__ == "__main__":
    main()
