#!/usr/bin/env python3
"""Embed source-audited TileLang PTX artifacts in a C++ include."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _c_string(name: str, source: Path) -> str:
    payload = source.read_text()
    lines = payload.splitlines(keepends=True)
    if payload and (not lines or not lines[-1].endswith("\n")):
        lines[-1] += "\n"
    body = "\n".join(json.dumps(line, ensure_ascii=True) for line in lines)
    return f"static constexpr char {name}[] =\n{body};\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--partial", type=Path, required=True)
    parser.add_argument("--combine", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    expected = manifest["artifacts"]
    for name, path in (("partial.ptx", args.partial), ("combine.ptx", args.combine)):
        actual = _sha256(path)
        wanted = expected[name]["sha256"]
        if actual != wanted:
            raise SystemExit(f"{name} hash mismatch: {actual} != {wanted}")

    manifest_hash = _sha256(args.manifest)
    header = (
        "// Generated by tools/v100/embed_tilelang_ptx.py; do not edit.\n"
        f"// Source: {manifest['source_repository']}@{manifest['source_commit']}\n"
        f"// TileLang: {manifest['tilelang_version']}; manifest sha256: {manifest_hash}\n"
        f"// partial.ptx sha256: {expected['partial.ptx']['sha256']}\n"
        f"// combine.ptx sha256: {expected['combine.ptx']['sha256']}\n"
    )
    content = (
        header
        + _c_string("kDFlashTileLangPartialPtx", args.partial)
        + "\n"
        + _c_string("kDFlashTileLangCombinePtx", args.combine)
    )
    args.output.write_text(content)
    print(args.output)


if __name__ == "__main__":
    main()
